---
- name: Ensure Screenshots directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/Pictures/ScreenShots"
    state: directory
    mode: '0755'

- name: Apply macOS defaults
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ macos_defaults }}"
  loop_control:
    label: "{{ item.domain }} {{ item.key }}"
  notify: refresh macos ui
