# ==================================================
# Prompt
# ==================================================

# Initialization
eval "$(starship init zsh)"

# Cache the prompt templates generated by Starship
_STARSHIP_SAVED_PROMPT="$PROMPT"
_STARSHIP_SAVED_RPROMPT="$RPROMPT"

# --------------------------------------------------
# Transient prompt
# --------------------------------------------------

autoload -Uz add-zle-hook-widget

# Define what the PAST line should shrink to
starship_transient_prompt() {
    print -P "%F{green}❯%f"
}

starship_transient_rprompt() {
    print -n ""
}

# This runs when you press Enter (shrinks the current line)
starship-transient-prompt-func() {
    PROMPT="$(starship_transient_prompt) "
    RPROMPT="$(starship_transient_rprompt)"
    zle .reset-prompt
}
add-zle-hook-widget zle-line-finish starship-transient-prompt-func

# This runs BEFORE the next prompt loads, restoring full Starship
setup_full_starship_prompt() {
    # Simply restore the original cached variables instead of re-running eval
    PROMPT="$_STARSHIP_SAVED_PROMPT"
    RPROMPT="$_STARSHIP_SAVED_RPROMPT"
}
precmd_functions+=(setup_full_starship_prompt)

